name: scalable_flutter_app_pro
description: A scalable Flutter app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Common
  flutter_bloc: ^8.1.3
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  go_router: ^11.1.3
  package_info_plus: ^4.2.0
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  intl: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.1
  purchases_flutter: ^6.2.0
  shared_preferences: ^2.2.2
  flutter_keyboard_visibility: ^5.4.1
  mixpanel_flutter: ^2.1.1
  image_picker: ^1.0.4
  in_app_review: ^2.0.8
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  flutter_local_notifications: ^16.1.0
  dio: ^5.3.3
  flutter_loggy_dio: ^3.0.1

  # Firebase
  firebase_core: ^2.20.0
  firebase_analytics: ^10.6.2
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.1
  cloud_functions: ^4.5.2
  firebase_crashlytics: ^3.4.3
  firebase_remote_config: ^4.3.3
  firebase_storage: ^11.5.0
  firebase_messaging: ^14.7.4

  # iOS
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
